Updated Postgre module to use pgx instead of pq
gofiber/storage pull request #153
Opened 2021-07-02 22:06 UTC by Technerder

Removed Postgre Close test since the pgx implementation of Close() doesn't return an error,
Removed Storage.Close()'s return method since the pgx implementation of Close() doesn't return an error,
Removed Config.maxIdleConns since pgx implementation doesn't support setting a maximum number of idle connections

2021-07-05 02:23 UTC, hi019 commented
Thanks for the PR! There are quiet a few breaking changes here. We'll need to release a new major version of the postgres implementation.

2021-07-05 03:44 UTC, Technerder commented
Is there anything I could change or do to help?

2021-07-06 09:45 UTC, ReneWerner87 commented on postgres/README.md
> -func (s *Storage) Close() error
please do not change the signature

2021-07-06 09:46 UTC, ReneWerner87 commented on postgres/postgres.go
> +func (s *Storage) Close() {
please do not change the signature

2021-07-06 09:48 UTC, ReneWerner87 requested changes

2021-07-06 09:48 UTC, ReneWerner87 commented on postgres/postgres_test.go
> -func Test_Postgres_Close(t *testing.T) {
the store still has a close method, what reason is there for you to remove the test? please adjust it to the new conditions

2021-07-09 06:41 UTC, ReneWerner87 commented
>  I asked the developer of pgx as to whether or not there was a way to find out if  pgxpool.Pool.Close() fails and they said that it simply blocks until it succeeds like I originally thought. I only removed the Test_Postgres_Close test because I thought it was redundant since the close method can't seem to fail. I also only modified the signature for the storage's Close method for the same reason

please add the test again to test the error free process

> I'd be more than happy to change the signature back and make it return nil for the error but I'm not sure if that'd be considered best practice.

https://github.com/gofiber/fiber/blob/master/app.go#L66
we have several storages, it is important that they all use the same interface, otherwise you cannot use them as intended, please just change the return type

2021-07-09 17:33 UTC, Technerder commented
> we have several storages, it is important that they all use the same interface, otherwise you cannot use them as intended, please just change the return type

So I assume adding something like the following would be frowned down upon unless I also added it to all other storage implementations?

```go
func (s *Storage) DB() *pgxpool.Pool {
	return s.db
}
```

2021-07-09 19:24 UTC, ReneWerner87 commented
No would be okay

2021-07-09 20:06 UTC, Technerder commented
Awesome, should I rename the function to ``GetDB`` or just add it in as ``DB``?

2021-07-11 23:20 UTC, hi019 commented
Thanks for all the work you've done here. If we're going to release a new major version, what would you think of rewriting the config to just accept a pgx connection, as you wrote in your issue? We would be able to remove a lot of code.

2021-07-12 00:31 UTC, Technerder commented
I'll start working on changing the module to accept a pgx object instead.

2021-07-12 00:39 UTC, Technerder commented
> Thanks for all the work you've done here. If we're going to release a new major version, what would you think of rewriting the config to just accept a pgx connection, as you wrote in your issue? We would be able to remove a lot of code.

Should I remove the postgres config struct altogether? I think it would make sense to do so.

2021-07-12 00:46 UTC, hi019 commented
Yeah, we should remove the config keys that correspond to the connection configuration.

2021-07-12 00:47 UTC, hi019 commented
But before you make changes, @ReneWerner87 what do you think of the idea?

2021-07-12 06:53 UTC, ReneWerner87 commented
passing the connection would be okay for me

2021-07-12 21:30 UTC, Technerder commented
I'll start implementing this right now.  I'm thinking of modifying the Config to look somewhat like this
```go
// Config defines the config for storage.
type Config struct {
	// DBPool pgxpool.Pool object
	//
	// Required
	DBPool pgxpool.Pool

	// Table name
	//
	// Optional. Default is "fiber_storage"
	Table string

	// Reset clears any existing keys in existing Table
	//
	// Optional. Default is false
	Reset bool

	// Time before deleting expired keys
	//
	// Optional. Default is 10 * time.Second
	GCInterval time.Duration
}
```

But I'm unsure of how to go about modifying the defaultConfig, should it just panic out if no DBPool object is passed in or should I remove the defaultConfig altogether?

2021-07-15 15:13 UTC, hi019 commented
@Technerder Yes, panicking should be fine here

2021-07-15 23:53 UTC, Technerder commented
Latest commit should allow people to directly pass in a pgxpool.Pool object as opposed to the database host, port, etc

2021-07-16 18:14 UTC, ReneWerner87 approved these changes

2021-07-16 18:18 UTC, ReneWerner87 commented
@Technerder please check 
![image](https://user-images.githubusercontent.com/7063188/125991764-186883b7-f33f-4d77-9b54-42b854f41bb8.png)
and 
![image](https://user-images.githubusercontent.com/7063188/125991790-99a3508f-c886-409c-9e0b-f2c30a31d260.png)

2021-07-18 16:43 UTC, Technerder commented
@ReneWerner87 I asked the developer of pgx about the dependency ([related issue](https://github.com/jackc/pgx/issues/1046)) and this is what they told me

> My first though was: why does a database driver have a dependency on a JWT library? As it turns out, there isn't any production dependency. It is there because of how modules include all the dependencies including tests in go.sum. It appears it is coming from go-kit. 48f3934 trimmed the go-kit dependency so I think this pseudo-dependency should drop entirely at some point.

Its only being used for some test, not in the actual library code.

2021-07-26 06:06 UTC, ReneWerner87 commented
@Technerder 
![image](https://user-images.githubusercontent.com/7063188/126940675-ecc95fe8-c51e-48aa-8241-c4f3e5ebb3d4.png)


and the snyk check failed
![image](https://user-images.githubusercontent.com/7063188/126940820-82fd5e19-89dd-453f-8ff2-3a13c531f326.png)

2021-07-26 13:03 UTC, hi019 commented
One more thing, can you put the new code in a v2 folder? That way we can issue a new major version with a /v2 import

2021-07-26 19:05 UTC, Technerder commented
> @Technerder
> ![image](https://user-images.githubusercontent.com/7063188/126940675-ecc95fe8-c51e-48aa-8241-c4f3e5ebb3d4.png)
> 
> and the snyk check failed
> ![image](https://user-images.githubusercontent.com/7063188/126940820-82fd5e19-89dd-453f-8ff2-3a13c531f326.png)

Would you be able to confirm if this is related to CVE-2021-3538?

2021-07-26 19:06 UTC, Technerder commented
> One more thing, can you put the new code in a v2 folder (so the path will be `postgres/v2/`)? That way we can issue a new major version with a /v2 import

Should I keep the v1 code there in the base folder?

2021-07-27 00:47 UTC, hi019 commented
Yep

2021-12-09 05:38 UTC, Technerder commented
Verification for "Tech#0067" in joeyxyz's dms

2022-01-09 22:03 UTC, sixcolors commented
@ReneWerner87 @Technerder just a comment re the 'security' issue with jackc/pg-con jackc/pg-mock it's a circular dependancy issue that only affects tests. If you check the build deps the vulnerable deps are not included. An issue with how snyk builds and evaluates its dependancy graph (ie build and test dependancies don't show up differently in the go.mod file).

https://github.com/jackc/pgx/issues/1054

2022-08-08 20:16 UTC, rishavs commented
Hey folks, checking back on this PR. 
PQ is in maintenance mode now and its maintainers even recommend pgx. https://github.com/lib/pq#status

If this PR is ready, it will be good to merge it as soon as possible, so that we can start using a postgres driver which is in active development.

2022-10-08 07:02 UTC, efectn commented
@Technerder pgx v5 seems to be ready for production. Can you test it? The problem should be fixed

2022-10-09 21:04 UTC, Technerder commented
@efectn I can test the code usage and functionality by tomorrow but I believe I lack the perms to run a Snyk security check/audit (unless I'm mistaken) and had to ask @ReneWerner87 the last time.

2022-10-09 21:25 UTC, efectn commented
![Screenshot_20221010-002347_Chrome](https://user-images.githubusercontent.com/45270788/194780078-0f2a64b4-3641-4cb8-a3e0-958a01460dcc.png)
![Screenshot_20221010-002326_Chrome](https://user-images.githubusercontent.com/45270788/194780083-9582a5c7-bc3b-483c-a3a1-408054321135.png)

Satori uuid seems to be removed. Maybe we need to open an issue for these alerts @Technerder

2022-10-10 05:14 UTC, Technerder commented
@efectn would you be able to provide a link to that page? I'm also a little confused about why `yaml.v3` is being flagged since the `go.mod` on the main `pgx` repo shows the current version being used to be `v3.0.1` [as shown here](https://github.com/jackc/pgx/blob/master/go.mod#L19) which should remove the vulnerability according to the screenshot.

2022-10-10 06:17 UTC, efectn commented
> @efectn would you be able to provide a link to that page? I'm also a little confused about why `yaml.v3` is being flagged since the `go.mod` on the main `pgx` repo shows the current version being used to be `v3.0.1` [as shown here](https://github.com/jackc/pgx/blob/master/go.mod#L19) which should remove the vulnerability according to the screenshot.

- github.com/gofiber/storage/postgres@0.0.0 › github.com/jackc/pgx@v5.0.2 › golang.org/x/crypto@v0.0.0-20220829220503-c86fa9a7ed90 › golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2
- github.com/gofiber/storage/postgres@0.0.0 › github.com/jackc/pgx@v5.0.2 › github.com/jackc/puddle@v2.0.0 › github.com/stretchr/objx@v0.4.0 › github.com/stretchr/testify@v1.7.1 › gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c

🤔🤔

2022-10-25 17:40 UTC, efectn commented
Created an issue --> https://github.com/jackc/pgx/issues/1352

2022-11-03 22:59 UTC, sixcolors commented
From a dependancy CVE standpoint I think we should move forward with this PR review.

Per my comments here https://github.com/jackc/pgx/issues/1352 Snyk go.mod scanning issues are false positives. Checked with govulncheck.

```
~/Documents/GitHub/storage/postgres (pr/153) » govulncheck ./...                                                                                               sixcolors@Jasons-MacBook-Pro
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
No vulnerabilities found.
```

2022-11-04 16:56 UTC, efectn commented
All test seems OK but i'm not big fan of adding pgx into the `postgres/v2`. I think it should be another else storage interface named `pgx`. What do you think @Technerder @ReneWerner87

2022-11-04 16:57 UTC, efectn commented
> From a dependancy CVE standpoint I think we should move forward with this PR review.
> 
> Per my comments here [jackc/pgx#1352](https://github.com/jackc/pgx/issues/1352) Snyk go.mod scanning issues are false positives. Checked with govulncheck.
> 
> ```
> ~/Documents/GitHub/storage/postgres/v2 (pr/153) » govulncheck .                                                                                            1 ↵ sixcolors@Jasons-MacBook-Pro
> govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.
> 
> Scanning for dependencies with known vulnerabilities...
> No vulnerabilities found.
> ```
> 
> And checking which packages are acutally used in v2
> 
> ```
> ~/Documents/GitHub/storage/postgres/v2 (pr/153) » go list -deps -f '{{define "M"}}{{.Path}}@{{.Version}}{{end}}{{with .Module}}{{if not .Main}}{{if .Replace}}{{template "M" .Replace}}{{else}}{{template "M" .}}{{end}}{{end}}{{end}}' | sort -u
> github.com/jackc/pgpassfile@v1.0.0
> github.com/jackc/pgservicefile@v0.0.0-20200714003250-2b9c44734f2b
> github.com/jackc/pgx/v5@v5.0.4
> github.com/jackc/puddle/v2@v2.0.0
> golang.org/x/crypto@v0.1.0
> golang.org/x/text@v0.4.0
> ```

We removed snyk thanks

2022-11-04 20:37 UTC, Technerder commented
> All test seems OK but i'm not big fan of adding pgx into the `postgres/v2`. I think it should be another else storage interface named `pgx`. What do you think @Technerder @ReneWerner87

I think removing the older interface with the now deprecated `lib/pq` library would be a good idea since like it's [README](https://github.com/lib/pq/blob/master/README.md#status)suggests it is going to be in maintenance mode. But I think it'd be a breaking change if we just completely removed the current v1 implementation. An alternative way to handle this migration would be to transparently to the user update the v1 package to make use of pgx, that way we could get rid of `lib/pg` entirely and use `pgx` in all implementations,

2022-11-05 08:18 UTC, ReneWerner87 commented
Somehow we need to declare this as a breaking change and prevent others from automatically updating without being aware of it

2 different storage would only confuse, since from the outside should not necessarily be known about the internal usages and both are postgresql

Unfortunately we push all storages together in one versions number so no differentiation can be made

So my tendency goes to the current v2 implementation

@efectn 
Or we try to make this monorepo multiversionable

2022-11-05 12:05 UTC, efectn commented
> Somehow we need to declare this as a breaking change and prevent others from automatically updating without being aware of it
> 
> 2 different storage would only confuse, since from the outside should not necessarily be known about the internal usages and both are postgresql
> 
> Unfortunately we push all storages together in one versions number so no differentiation can be made
> 
> So my tendency goes to the current v2 implementation
> 
> @efectn Or we try to make this monorepo multiversionable

It sounds better to make this repo multiversionable

2022-11-05 12:11 UTC, ReneWerner87 commented
Then let us doing some bit of research

2022-11-05 12:36 UTC, sixcolors commented
Why can’t we just make this API compatible?

I don’t think most users care what package we use behind the scenes.

2022-11-05 16:22 UTC, ReneWerner87 commented
But it's not possible since the type of storage.Conn() is different

2022-11-20 10:43 UTC, ReneWerner87 commented
maybe we should use the solutions from https://github.com/awslabs/aws-go-multi-module-repository-tools

2023-03-12 17:58 UTC, ReneWerner87 approved these changes

2023-03-12 17:58 UTC, merged