🚀 Add S3 Implementation
gofiber/storage pull request #227
Opened 2021-10-01 21:01 UTC by pcen

Adds S3 implementation of the Storage interface

2021-10-04 06:41 UTC, ReneWerner87 reviewed
please add the new storage in the workflow files in the root of the repository under .github

2021-10-05 16:57 UTC, pcen commented
Added workflow for s3. Currently there are no unit tests for s3 functionality and it would require a lot of code to mock s3 in unit tests.

2021-10-14 02:40 UTC, hi019 commented
So if I understand correctly:

You're saying that by avoiding the user having to pass in a specific version of the S3 SDK, this implementation can be updated if the SDK receives improvements (without the user having to change anything)?

2022-01-12 20:27 UTC, tomaswarynyca commented
@pcen any news about finishing this?

2022-01-20 04:24 UTC, pcen commented
> @pcen any news about finishing this?

The code functionally all works, @hi019 requested changes for some small code cleanup, otherwise all that's left is to somehow test with the GitHub CI, I haven't had time to look into how to do it, but if someone else figures it out before I have time to it's ready to merge

2022-02-02 16:31 UTC, efectn commented
I need s3 in one of my projects and this storage can ease my work. So i'll try to finish this PR. 

Btw i'm not sure about SDK version. What about using v2? @pcen

2022-02-02 21:47 UTC, pcen commented
> I need s3 in one of my projects and this storage can ease my work. So i'll try to finish this PR.
> 
> Btw i'm not sure about SDK version. What about using v2? @pcen

When I started, I don't think v2 was available. Looking at the Amazon SDK repo for golang, it looks like the latest release is on [v1.42.45](https://github.com/aws/aws-sdk-go/releases/tag/v1.42.45). If you use the latest release version, it shouldn't cause any issues. If there is a newer version of the SDK, until it is implemented in golang, it won't effect us.

2022-02-02 21:55 UTC, efectn commented
> > I need s3 in one of my projects and this storage can ease my work. So i'll try to finish this PR.
> > Btw i'm not sure about SDK version. What about using v2? @pcen
> 
> When I started, I don't think v2 was available. Looking at the Amazon SDK repo for golang, it looks like the latest release is on [v1.42.45](https://github.com/aws/aws-sdk-go/releases/tag/v1.42.45). If you use the latest release version, it shouldn't cause any issues. If there is a newer version of the SDK, until it is implemented in golang, it won't effect us.

Amazon has repo for go v2 sdk (https://github.com/aws/aws-sdk-go-v2)

Btw we need to enter env variables(creditianals) for exexuting tests. I think we don't need to add tests because of that. Like https://github.com/gofiber/storage/blob/main/dynamodb/dynamodb_test.go

@ReneWerner87 @hi019 What do you think?

2022-02-02 22:25 UTC, pcen commented
> > > I need s3 in one of my projects and this storage can ease my work. So i'll try to finish this PR.
> > > Btw i'm not sure about SDK version. What about using v2? @pcen
> > 
> > 
> > When I started, I don't think v2 was available. Looking at the Amazon SDK repo for golang, it looks like the latest release is on [v1.42.45](https://github.com/aws/aws-sdk-go/releases/tag/v1.42.45). If you use the latest release version, it shouldn't cause any issues. If there is a newer version of the SDK, until it is implemented in golang, it won't effect us.
> 
> Amazon has repo for go v2 sdk (https://github.com/aws/aws-sdk-go-v2)
> 
> Btw we need to enter env variables(creditianals) for exexuting tests. I think we don't need to add tests because of that. Like https://github.com/gofiber/storage/blob/main/dynamodb/dynamodb_test.go
> 
> @ReneWerner87 @hi019 What do you think?

Had no idea about v2! in which case, we should definitely be using it!

2022-02-03 13:05 UTC, ReneWerner87 requested changes
please check all workflows, think something needs to be adjusted there, add the new storage to the readme in the root, so this is obvious as storage variant 

and the unittests are still insufficient, they need to be extended, so we can deliver the quality the users are expecting from us

2022-02-03 15:11 UTC, ReneWerner87 approved these changes

2022-02-03 21:05 UTC, ReneWerner87 approved these changes

2022-02-04 05:06 UTC, hi019 requested changes
Thanks for finishing this 👍

2022-02-04 05:06 UTC, hi019 commented on s3/s3.go
> +	// If config fields of credentials not given, credentials are using from the environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY), ~/.aws/credentials, or EC2 instance role.
We should put this in the readme. Or better yet just link to https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specifying-credentials

2022-02-04 05:06 UTC, hi019 commented on s3/s3.go
> +	if len(key) <= 0 || len(val) <= 0 {
What if a user wants to insert an empty file?

2022-02-04 11:41 UTC, merged