Add support to MSSQL
gofiber/storage pull request #587
Opened 2022-10-25 15:14 UTC by gandaldf

I hope this can be useful to the project.
Let me know if I need to fix anything!

2022-10-25 15:21 UTC, efectn commented
Can you add some workflows

2022-10-25 22:36 UTC, gandaldf commented
I'm sorry I don't know what else I have to do... it's my first time with workflows and I don't really know what I'm doing.
In addition to this, the mssql docker image is one of the most difficult since it does not have the possibility to create a database at boot time like all the others except with an additional procedure.

2022-11-03 10:53 UTC, ReneWerner87 requested changes
please use the updated fork https://github.com/microsoft/go-mssqldb/releases/tag/v0.16.0 instead of the origin package

they fixed the security issued 
https://github.com/denisenkom/go-mssqldb/compare/master...microsoft:go-mssqldb:main#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

2022-11-03 15:48 UTC, ReneWerner87 approved these changes

2022-11-03 15:48 UTC, merged