Add benchmarks for storage drivers
gofiber/storage pull request #992
Opened 2023-09-14 21:13 UTC by efectn

closes https://github.com/gofiber/storage/issues/968

2023-09-16 16:24 UTC, gaby requested changes

2023-09-16 16:24 UTC, gaby commented on .github/workflows/benchmark.yml
> +          redis-server --tls-port 6380 --port 6379 \
All the other DB's are not using TLS, we should remove it for the Benchmark of Redis and Ruedis.

TLS is known to cause performance issues for Redis in terms of Op/sec

2023-09-16 16:24 UTC, gaby commented on .github/workflows/benchmark.yml
> +          redis-server --tls-port 6380 --port 6379 \
Seems the TestStore doesnt use TLS, so we dont need to do all this setup for the Benchmarks

2023-09-16 17:30 UTC, gaby approved these changes

2023-09-16 17:31 UTC, gaby commented
May be good to wait until #993 is merged, but overall LGTM 💪

2023-09-18 05:49 UTC, ReneWerner87 approved these changes

2023-09-18 05:50 UTC, merged